# Generated by Django 3.0 on 2019-12-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(verbose_name='date uploaded')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('retrieved_text', models.TextField(blank=True, null=True, verbose_name='retrieved text')),
            ],
            options={
                'verbose_name': 'check',
                'verbose_name_plural': 'checks',
            },
        ),
    ]
